trigger:
  branches:
    include:
      - master

variables:
  # Name of the Azure Agent Pool, Windows type.
  - name: agent_pool_name
    value: CUSTOM_WINDOWS
  # Name of the package to be pulled and deployed.
  - name: package_name
    value: MyApplication
  - name: package_feed
    value: UniversalPackageFeed
  - name: service_dir
    value: "O:\AppService\"



parameters:
  - name: acc_env
    displayName: 'ACC Environment Config'
    type: object
    default:
      name: acc
      host: <ACC_HOST>
      username: <ACC_USERNAME>
      package_version: 1.0.0
      vaultName: <ACC_VAULT_NAME>
      subscription: <ACC_SUBSCRIPTION_ID>

  - name: prd_env
    displayName: 'PRD Environment Config'
    type: object
    default:
      name: prd
      host: <PRD_HOST>
      username: <PRD_USERNAME>
      package_version: 1.0.0
      vaultName: <PRD_VAULT_NAME>
      subscription: <PRD_SUBSCRIPTION_ID>

jobs:
  - job: DeployToAcc
    displayName: 'Deploy to ${{ parameters.acc_env.name }}'
    pool:
      name: ${{ variables.agent_pool_name }}
    steps:
      - task: AzureKeyVault@2
        displayName: 'Retrieve secrets from ACC Key Vault'
        inputs:
          azureSubscription: ${{ parameters.acc_env.subscription }}
          KeyVaultName: ${{ parameters.acc_env.vaultName }}
          SecretsFilter: '*'
          RunAsPreJob: true

      - template: deploy-template.yaml
        parameters:
          environment: ${{ parameters.acc_env.name }}
          package_feed: ${{ variables.package_feed }}
          package_name: ${{ variables.package_name }}
          package_version: ${{ parameters.acc_env.package_version }}
          service_dir: ${{ variables.service_dir }}
          host: ${{ parameters.acc_env.host }}
          username: ${{ parameters.acc_env.username }}
          password: '$(deploy_user_password)'

  - job: DeployToPrd
    displayName: 'Deploy to ${{ parameters.prd_env.name }}'
    pool:
      name: ${{ variables.agent_pool_name }}
    steps:
      - task: AzureKeyVault@2
        displayName: 'Retrieve secrets from PRD Key Vault'
        inputs:
          azureSubscription: ${{ parameters.prd_env.subscription }}
          KeyVaultName: ${{ parameters.prd_env.vaultName }}
          SecretsFilter: '*'
          RunAsPreJob: true

      - template: deploy-template.yaml
        parameters:
          environment: ${{ parameters.prd_env.name }}
          package_feed: ${{ variables.package_feed }}
          package_name: ${{ variables.package_name }}
          package_version: ${{ parameters.prd_env.package_version }}
          service_dir: ${{ variables.service_dir }}
          host: ${{ parameters.prd_env.host }}
          username: ${{ parameters.prd_env.username }}
          password: '$(deploy_user_password)'
